// Static import so Vercel Output File Tracing sees the dependency and
// includes dist/server.cjs in the serverless function bundle at deploy time.
// @ts-ignore - .cjs file is generated by the build step before function compilation.
import serverModule from '../dist/server.cjs';
import type { Request, Response } from 'express';

const app: any = (serverModule as any)?.default ?? serverModule;

// Handle the (very unlikely) case where the bundled server module has no export.
function fallback(_req: Request, res: Response) {
  res.status(500).json({
    error: 'Server bundle missing default export',
  });
}

export default function handler(req: Request, res: Response) {
  if (typeof app === 'function') {
    app(req, res);
  } else {
    fallback(req, res);
  }
}
